# ------------------------------------------------------------------
# Output
# ------------------------------------------------------------------

output_dir: "/home/INT/laffitte.z/code/these/data/compar"

# ------------------------------------------------------------------
# Input data
# ------------------------------------------------------------------

data_dir: "/envau/work/meca/data/test_retest_datatbase/HCP_test_retest"
atlas_dir: "/envau/work/meca/data/atlas_glasser2016/Glasser_et_al_2016_HCP_MMP1.0_kN_RVVG/Q1-Q6_RelatedValidation210/MNINonLinear/fsaverage_LR32k/Q1-Q6_RelatedValidation210"
data_test: "/envau/work/meca/users/2025_laffite.z/data/textures_for_zoe_all"

dir:
  rawdata: "HCP_rawdata"
  pitsdata: "HCP_sulcal_pits"

sources:
  native: "T1w/Native"
  reg: "MNINonLinear/Native"
  pits: "sulcal_pits_baseline"

mesh_types:
  pial: "pial.native"
  white: "white.native"
  white.template: "white_MSMAll_2_d41_WRN_DeDrift.32k_fs_LR"
  sphere: "sphere.native"
  sphere.reg: "sphere.MSMAll.native"
  sphere.template: "sphere.32k_fs_LR"
  aparc: "aparc.native.label"
  curv: "curvature.native.shape"
  basin: "basins_100.0_0.005_0.0"


side: "L"
thr_basins: 0.8


# ------------------------------------------------------------------
# Environments
# ------------------------------------------------------------------
environments:
  slam: "../envs/env_slam.yml"


# ------------------------------------------------------------------
# Software
# ------------------------------------------------------------------
software:
  able: "../software/ABLE"

# ------------------------------------------------------------------
# Containers
# ------------------------------------------------------------------
containers:
  # mindboggle: "../images/mindboggle.sif"
  # trace: "../images/trace.sif"
  # able: "../images/able.sif"
  # brainvisa: "/hpc/shared/apps/x86_64/softs/singularity_images/brainvisa-5.0.4.sif"
  # matlab: ""
  # singularity: ""

  mindboggle: "docker://nipy/mindboggle"
  trace: "docker://ilwoolyu/cmorph:1.7"
  able: "docker://albertofpena/able:latest"
  brainvisa: "https://brainvisa.info/download/brainvisa-5.0.4.sif"
